# Generated by Django 2.2.10 on 2020-07-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0004_auto_20200727_1657'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 16, 57, 33, 417194)),),
    ]
