# Generated by Django 2.2.10 on 2020-07-28 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0005_auto_20200727_1657'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 1, 34, 231160)),),
    ]
