# Generated by Django 2.2.10 on 2020-07-29 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0006_auto_20200728_1901'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 22, 20, 56, 593446)),),
    ]
