# Generated by Django 2.2.10 on 2020-07-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0010_auto_20200728_2154'),
        ('food_detection', '0007_auto_20200729_2220'),
    ]

    operations = []
