# Generated by Django 2.2.10 on 2020-08-01 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0011_merge_20200730_1929'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 50, 29, 779048)),),
    ]
