# Generated by Django 2.2.10 on 2020-08-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0012_auto_20200801_0950'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 14, 43, 51, 819739)),),
    ]
