# Generated by Django 2.2.10 on 2020-08-01 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0024_auto_20200801_2223'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 23, 25, 13, 639328)),),
    ]
