# Generated by Django 2.2.10 on 2020-08-01 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0031_auto_20200802_0058'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 1, 57, 42, 407198)),),
    ]
