# Generated by Django 2.2.10 on 2020-08-02 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0032_auto_20200802_0157'),
    ]

    operations = [
        migrations.AlterField(model_name='filehash', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 4, 24, 39, 457977)),),
    ]
