# Generated by Django 2.2.10 on 2020-08-03 01:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20200803_0717'),
        ('food_detection', '0034_auto_20200803_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=70)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 8, 3, 7, 17, 31, 678287))),
                ('expected_item_name', models.CharField(max_length=40)),
                ('provided_item', models.CharField(max_length=40)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.DeleteModel(name='FileHash',),
    ]
