# Generated by Django 2.2.10 on 2020-08-03 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0035_auto_20200803_0717'),
    ]

    operations = [
        migrations.AddField(model_name='alert', name='url', field=models.CharField(default='', max_length=70), preserve_default=False,),
        migrations.AlterField(model_name='alert', name='datetime', field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 12, 32, 1, 614171)),),
    ]
