# Generated by Django 2.2.10 on 2020-08-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(name='parent', options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},),
        migrations.AlterModelOptions(name='student', options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},),
    ]
