# Generated by Django 2.2.10 on 2020-08-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200801_2325'),
    ]

    operations = [
        migrations.AddField(model_name='student', name='aadhaar_card_image', field=models.ImageField(blank=True, null=True, upload_to='aadhaar_cards'),),
        migrations.AddField(model_name='student', name='student_image', field=models.ImageField(blank=True, null=True, upload_to='student_images'),),
    ]
