# Generated by Django 2.2.10 on 2020-08-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200802_0058'),
    ]

    operations = [
        migrations.AddField(model_name='parent', name='contact_no', field=models.PositiveIntegerField(blank=True, null=True),),
        migrations.AddField(model_name='parent', name='email', field=models.EmailField(blank=True, max_length=255, null=True, unique=True),),
    ]
