const data = {
  en: {
    LOGIN_HEADER: 'LOGIN',
    LOGIN_SUBHEADER: 'Welcome to Cisco',
    EMAIL: 'EMAIL',
    PASSWORD: 'PASSWORD',
    LOGIN_BTN: 'LOGIN',
    DASHBOARD: {
      HEADER: 'List of schools',
      PRINCIPAL: 'Principal',
      NOS: 'Number of Students',
      NOW: 'Number of Workers',
      BTN_TEXT: 'View Details',
    },
    SCHOOL_PAGE: {
      HEADER: 'Statistics',
      CARDS: {
        OPTION1: 'Average Nutritional Consumption per Student',
        OPTION2: 'Gender Ratio',
        OPTION3: 'Attendance',
      },
      MENU: {
        BF: 'Breakfast Menu',
        BT: 'Breakfast Time',
        LF: 'Lunch Menu',
        LT: 'Lunch Time',
        OFFICIAL: 'Official',
        STATUS: 'Status',
      },
    },
  },
  hi: {
    LOGIN_HEADER: 'लॉग इन करें',
    LOGIN_SUBHEADER: 'सिस्को में आपका स्वागत है',
    EMAIL: 'ईमेल',
    PASSWORD: 'कुंजिका',
    LOGIN_BTN: 'लॉग इन करें',
    DASHBOARD: {
      HEADER: 'स्कूलों की सूची',
      PRINCIPAL: 'प्रधान अध्यापक',
      NOS: 'छात्रों की संख्या',
      NOW: 'श्रमिकों की संख्या',
      BTN_TEXT: 'विवरण देखें',
    },
    SCHOOL_PAGE: {
      HEADER: 'आंकड़े',
      CARDS: {
        OPTION1: 'पति छात्र औसत पोषण की खपत',
        OPTION2: 'लिंग अनुपात',
        OPTION3: 'उपस्थिति',
      },
      MENU: {
        BF: 'नाश्ता मेनू',
        BT: 'नाश्ते का समय',
        LF: 'दोपहर के भोजन का मेनू',
        LT: 'लंच टाइम',
        OFFICIAL: 'आधिकारिक',
        STATUS: 'स्थिति',
      },
    },
  },
  tel: {
    LOGIN_HEADER: 'ప్రవేశించండి',
    LOGIN_SUBHEADER: 'సిస్కోకు స్వాగతం',
    EMAIL: 'EMAIL',
    PASSWORD: 'పాస్వర్డ్',
    LOGIN_BTN: 'ప్రవేశించండి',
    DASHBOARD: {
      HEADER: 'పాఠశాలల జాబితా',
      PRINCIPAL: 'ప్రిన్సిపాల్',
      NOS: 'విద్యార్థుల సంఖ్య',
      NOW: 'కార్మికుల సంఖ్య',
      BTN_TEXT: 'వివరాలను చూడండి',
    },
    SCHOOL_PAGE: {
      HEADER: 'గణాంకాలు',
      CARDS: {
        OPTION1: 'ప్రతి విద్యార్థికి సగటు పోషక వినియోగం',
        OPTION2: 'లింగ నిష్పత్తి',
        OPTION3: 'హాజరు',
      },
      MENU: {
        BF: 'అల్పాహారం మెనూ',
        BT: 'అల్పాహార సమయం',
        LF: 'లంచ్ మెనూ',
        LT: 'భోజన సమయం',
        OFFICIAL: 'అధికారిక',
        STATUS: 'స్థితి',
      },
    },
  },
  guj: {
    LOGIN_HEADER: 'પ્રવેશ કરો',
    LOGIN_SUBHEADER: 'સિસ્કો પર આપનું સ્વાગત છે',
    EMAIL: 'EMAIL',
    PASSWORD: 'પાસવર્ડ',
    LOGIN_BTN: 'પ્રવેશ કરો',
    DASHBOARD: {
      HEADER: 'શાળાઓની સૂચિ',
      PRINCIPAL: 'આચાર્યશ્રી',
      NOS: 'વિદ્યાર્થીઓની સંખ્યા',
      NOW: 'કામદારોની સંખ્યા',
      BTN_TEXT: 'વિગતો જુઓ',
    },
    SCHOOL_PAGE: {
      HEADER: 'આંકડા',
      CARDS: {
        OPTION1: 'વિદ્યાર્થી દીઠ સરેરાશ પોષણ વપરાશ',
        OPTION2: 'લિંગ ગુણોત્તર',
        OPTION3: 'હાજરી',
      },
      MENU: {
        BF: 'સવારનો નાસ્તો મેનુ',
        BT: 'સવારનો નાસ્તો',
        LF: 'લંચ મેનુ',
        LT: 'બપોરનો જમવાનો સમય',
        OFFICIAL: 'અધિકારી',
        STATUS: 'સ્થિતિ',
      },
    },
  },
  pun: {
    LOGIN_HEADER: 'ਲਾਗਿਨ',
    LOGIN_SUBHEADER: 'ਸਿਸਕੋ ਵਿਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    EMAIL: 'ਈ - ਮੇਲ',
    PASSWORD: 'ਪਾਸਵਰਡ',
    LOGIN_BTN: 'ਲਾਗਿਨ',
    DASHBOARD: {
      HEADER: 'ਸਕੂਲਾਂ ਦੀ ਸੂਚੀ',
      PRINCIPAL: 'ਪ੍ਰਿੰਸੀਪਲ',
      NOS: 'ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਗਿਣਤੀ',
      NOW: 'ਵਰਕਰਾਂ ਦੀ ਗਿਣਤੀ',
      BTN_TEXT: 'ਵੇਰਵਾ ਵੇਖੋ',
    },
    SCHOOL_PAGE: {
      HEADER: 'ਅੰਕੜੇ',
      CARDS: {
        OPTION1: 'ਪ੍ਰਤੀ ਵਿਦਿਆਰਥੀ పోషణ ਪੋਸ਼ਣ ਸੰਬੰਧੀ ਖਪਤ',
        OPTION2: 'ਲਿੰਗ ਅਨੁਪਾਤ',
        OPTION3: 'ਹਾਜ਼ਰੀ',
      },
      MENU: {
        BF: 'ਨਾਸ਼ਤੇ ਵਿੱਚ ਮੀਨੂੰ',
        BT: 'ਨਾਸ਼ਤੇ ਦਾ ਸਮਾਂ',
        LF: 'ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਦੀ ਸੂਚੀ',
        LT: 'ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਦਾ ਸਮਾਂ',
        OFFICIAL: 'ਸਰਕਾਰੀ',
        STATUS: 'ਸਥਿਤੀ',
      },
    },
  },
};

export default data;
