# Generated by Django 2.2.10 on 2020-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('organisation_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=150, unique=True)),
            ],
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools',},
        ),
    ]
