# Generated by Django 2.2.10 on 2020-07-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('food_item', models.CharField(max_length=40)),],
            options={'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Items',},
        ),
        migrations.CreateModel(
            name='FoodSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={'verbose_name': 'Food Schedule', 'verbose_name_plural': 'Food Schedules',},
        ),
        migrations.CreateModel(
            name='FoodItemDayMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'day',
                    models.CharField(
                        choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=10
                    ),
                ),
                ('food_item', models.ManyToManyField(to='school.FoodItem')),
                ('of_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FoodSchedule')),
            ],
            options={'verbose_name': 'Food Item Day Map', 'verbose_name_plural': 'Food Item Day Maps',},
        ),
    ]
