# Generated by Django 2.2.10 on 2020-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_fooditem_fooditemdaymap_foodschedule'),
    ]

    operations = [
        migrations.AddField(model_name='school', name='url', field=models.CharField(default='', max_length=50, unique=True), preserve_default=False,),
    ]
