# Generated by Django 2.2.10 on 2020-07-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_url'),
    ]

    operations = [
        migrations.RenameField(model_name='school', old_name='url', new_name='URL',),
    ]
