# Generated by Django 2.2.10 on 2020-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200723_1555'),
    ]

    operations = [
        migrations.AlterField(model_name='foodschedule', name='category', field=models.CharField(choices=[('BR', 'BREAKFAST'), ('LN', 'LUNCH'), ('DN', 'DINNER')], max_length=20),),
    ]
