# Generated by Django 2.2.10 on 2020-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200723_1559'),
    ]

    operations = [
        migrations.AddField(model_name='school', name='district', field=models.CharField(blank=True, max_length=50),),
    ]
