# Generated by Django 2.2.10 on 2020-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200727_0800'),
    ]

    operations = [
        migrations.AlterField(model_name='school', name='URL', field=models.URLField(unique=True),),
        migrations.AlterField(model_name='school', name='contact_no', field=models.PositiveIntegerField(),),
    ]
