# Generated by Django 2.2.10 on 2020-08-01 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200731_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisors',},
        ),
        migrations.AddField(model_name='school', name='supervisor', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Supervisor'),),
    ]
