# Generated by Django 2.2.10 on 2020-08-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200801_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MENU', 'MENU ISSUE'), ('WORKER', 'WORKER ISSUE'), ('CAMERA', 'CAMERA ISSUE'), ('OTHER', 'OTHER')], max_length=20)),
                ('information', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={'verbose_name': 'Report Issue', 'verbose_name_plural': 'Report Issues',},
        ),
    ]
