# Generated by Django 2.2.10 on 2020-08-01 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_wastage'),
    ]

    operations = [
        migrations.AlterModelOptions(name='wastage', options={'verbose_name': 'Food Wastage in kg', 'verbose_name_plural': 'Food Wastages'},),
        migrations.RenameField(model_name='wastage', old_name='FoodSchedule', new_name='food_schedule',),
        migrations.AddField(model_name='wastage', name='date', field=models.DateField(default=datetime.date(2020, 8, 1)),),
    ]
