# Generated by Django 2.2.10 on 2020-08-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200801_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(name='wastage', options={'verbose_name': 'Food Wastage in kg/week', 'verbose_name_plural': 'Food Wastages'},),
    ]
