# Generated by Django 2.2.10 on 2020-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200801_1401'),
    ]

    operations = [
        migrations.AlterField(model_name='fooditem', name='nutrition', field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nutrition in calories/100g'),),
    ]
