# Generated by Django 2.2.10 on 2020-08-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200801_1402'),
    ]

    operations = [
        migrations.RemoveField(model_name='wastage', name='food_schedule',),
        migrations.AddField(model_name='foodschedule', name='wastage', field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Wastage'),),
    ]
