# Generated by Django 2.2.10 on 2020-08-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_report'),
        ('school', '0017_auto_20200801_1424'),
    ]

    operations = []
