# Generated by Django 2.2.10 on 2020-08-01 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('school', '0018_merge_20200801_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_present', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date(2020, 8, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name='school', name='supervisor',),
        migrations.AddField(model_name='school', name='under_supervisor', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),),
        migrations.DeleteModel(name='Supervisor',),
        migrations.AddField(model_name='contractor', name='school', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),),
    ]
