# Generated by Django 2.2.10 on 2020-08-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200801_2213'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='attendance', name='of_student', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student'),),
    ]
