# Generated by Django 2.2.10 on 2020-08-01 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20200801_2223'),
    ]

    operations = [
        migrations.AddField(model_name='contractor', name='username', field=models.CharField(default='', max_length=50, unique=True), preserve_default=False,),
        migrations.AlterField(model_name='attendance', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 16, 53, 46, 486430, tzinfo=utc)),),
        migrations.AlterField(model_name='wastage', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 16, 53, 46, 484436, tzinfo=utc)),),
    ]
