# Generated by Django 2.2.10 on 2020-08-01 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20200801_2325'),
    ]

    operations = [
        migrations.AlterField(model_name='attendance', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 18, 28, 20, 33097, tzinfo=utc)),),
        migrations.AlterField(model_name='school', name='under_supervisor', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),),
        migrations.AlterField(model_name='wastage', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 18, 28, 20, 27140, tzinfo=utc)),),
    ]
