# Generated by Django 2.2.10 on 2020-08-01 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_auto_20200802_0058'),
    ]

    operations = [
        migrations.AlterField(model_name='attendance', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 20, 27, 42, 406201, tzinfo=utc)),),
        migrations.AlterField(model_name='wastage', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 1, 20, 27, 42, 404207, tzinfo=utc)),),
    ]
