# Generated by Django 2.2.10 on 2020-08-02 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20200802_0157'),
    ]

    operations = [
        migrations.AlterField(model_name='attendance', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 2, 22, 54, 39, 454983, tzinfo=utc)),),
        migrations.AlterField(model_name='wastage', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 2, 22, 54, 39, 450983, tzinfo=utc)),),
    ]
