# Generated by Django 2.2.10 on 2020-08-03 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_auto_20200803_0548'),
    ]

    operations = [
        migrations.AlterField(model_name='attendance', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 3, 1, 47, 31, 676293, tzinfo=utc)),),
        migrations.AlterField(model_name='wastage', name='date', field=models.DateField(default=datetime.datetime(2020, 8, 3, 1, 47, 31, 674299, tzinfo=utc)),),
    ]
